mod_pos_ui <- function(id) { ns <- NS(id); tagList(h2("Point of Sale"), textInput(ns("search"), "Find available inventory"), DTOutput(ns("items")), h3("Cart"), tableOutput(ns("cart")), strong(textOutput(ns("total"))), selectInput(ns("payment"), "Payment method", PAYMENT_METHODS), numericInput(ns("tendered"), "Amount tendered", 0, min = 0), textOutput(ns("change")), actionButton(ns("checkout"), "Complete sale", class = "btn-success"), actionButton(ns("clear"), "Clear cart")) }
mod_pos_server <- function(id, employee_id, changed = reactiveVal(0)) {
  moduleServer(id, function(input, output, session) {
    cart <- reactiveVal(data.frame(item_id = integer(), item_name = character(), price = numeric()))
    available <- reactive({ changed(); data <- read_inventory(); data <- data[data$status == "Available", , drop = FALSE]; term <- tolower(trimws(input$search %||% "")); if (nzchar(term)) data <- data[grepl(term, tolower(paste(data$sku, data$item_name)), fixed = TRUE), , drop = FALSE]; data })
    output$items <- renderDT(datatable(available()[, c("item_id", "sku", "item_name", "asking_price", "condition"), drop = FALSE], selection = "single", rownames = FALSE))
    observeEvent(input$items_rows_selected, { row <- available()[input$items_rows_selected, ]; if (nrow(row)) cart(rbind(cart(), data.frame(item_id = row$item_id, item_name = row$item_name, price = row$asking_price))) })
    output$cart <- renderTable(cart()); total <- reactive(sum(cart()$price)); output$total <- renderText(paste("Total:", currency(total()))); output$change <- renderText(paste("Change:", currency(max(0, input$tendered - total()))))
    observeEvent(input$clear, cart(data.frame(item_id = integer(), item_name = character(), price = numeric())))
    observeEvent(input$checkout, { req(nrow(cart()) > 0, employee_id()); if (input$tendered < total()) return(showNotification("Amount tendered is insufficient.", type = "error")); inventory <- read_inventory(); if (any(!cart()$item_id %in% inventory$item_id[inventory$status == "Available"])) return(showNotification("One or more cart items are no longer available.", type = "error")); transactions <- read_transactions(); tx_id <- next_id(transactions, "transaction_id"); tx_number <- new_number("SALE-"); tx <- data.frame(transaction_id = tx_id, transaction_number = tx_number, employee_id = as.integer(employee_id()), total = total(), payment_method = input$payment, created_at = as.character(Sys.time())); write_csv(rbind(transactions, tx), file_paths$transactions); details <- read_csv(file_paths$transaction_items); new_details <- data.frame(transaction_item_id = next_id(details, "transaction_item_id"), transaction_id = tx_id, item_id = cart()$item_id, unit_price = cart()$price); write_csv(rbind(details, new_details), file_paths$transaction_items); inventory$status[inventory$item_id %in% cart()$item_id] <- "Sold"; inventory$updated_at[inventory$item_id %in% cart()$item_id] <- as.character(Sys.time()); write_csv(inventory, file_paths$inventory); showNotification(paste("Sale completed:", tx_number)); cart(data.frame(item_id = integer(), item_name = character(), price = numeric())); changed(changed() + 1) })
  })
}
